config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'
  
  resources :users, only: [:create, :new]
  resource :session, only: [:new, :create, :destroy]
  
  namespace :api, defaults: { format: :json } do
    resources :polls, except: [:new, :edit]
    resources :answer_choices, only: [:create, :update, :destroy]
    resources :responses, only: [:create]
    post 'url', to: 'urls#shorten'
  end
end

app/models/answer_choice.rb
class AnswerChoice < ActiveRecord::Base
  validates :poll, :body, :ord, presence: true

  belongs_to :poll, dependent: :destroy
  
  has_many :responses
  has_many :respondents, through: :responses
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  validates :user_id, :body, presence: true
  validates :answer_choices, length: { minimum: 2 }

  belongs_to :user

  has_many :answer_choices, inverse_of: :poll
  has_many :responses, through: :answer_choices
  has_many :respondents, through: :responses

  accepts_nested_attributes_for :answer_choices
end

app/models/response.rb
class Response < ActiveRecord::Base
  validate :user_hasnt_answered_poll

  validates :answer_choice_id, :respondent_id, presence: true
  validates :answer_choice_id, uniqueness: { scope: :respondent_id }

  belongs_to :answer_choice, dependent: :destroy, counter_cache: true

  belongs_to :respondent, 
            foreign_key: 'respondent_id', 
            class_name: 'User'
  has_one :poll, through: :answer_choice

  def user_hasnt_answered_poll
    if poll.respondents
      .where("answer_choices.id <> ?", self.answer_choice_id)
      .include?(respondent)
        
        errors.add(:poll, "Already answered")
    end
  end
end

    

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authored_polls,
            foreign_key: :user_id,
            class_name: 'Poll'
  has_many :responses,
            foreign_key: :respondent_id,
            class_name: 'Response'
  has_many :answered_polls, through: :responses, source: :poll

  validates :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, uniqueness: true, presence: true, unless: :guest?
  
  attr_reader :password
  after_initialize :ensure_session_token

  def self.find_by_credentials(user_params)
    user = User.find_by_username(user_params[:username])
    user.try(:is_password?, user_params[:password]) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def self.new_guest
    new { |u| u.guest = true }
  end

  protected

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

app/controllers/api/answer_choices_controller.rb
module Api
  class AnswerChoicesController < ApiController
    # using choice ivar instead of answer_choice to save typing
    def create
      @choice = current_poll.answer_choices.new(choice_params)
      
      if @choice.save
        render json: @choice
      else
        render json: @choice.errors.full_messages, status: :unprocessable_entity
      end
    end
    
    def update
      @choice = AnswerChoice.find(params[:id])
      if @choice.update_attributes(choice_params)
        render json: @choice
      else
        render json: @choice.errors.full_messages, status: :unprocessable_entity
      end
    end
    
    def destroy
      @choice = current_poll.answer_choices.find(params[:id])
      @choice.try(:destroy)
      render json: {}
    end
  
    private
    
    def current_poll
      if params[:id]
        @choice = AnswerChoice.find(params[:id])
        @poll = @choice.poll
      elsif params[:answer_choice]
        @poll = Poll.find(params[:answer_choice][:poll_id])
      end
    end
    
    def choice_params
      params.require(:answer_choice).permit(:poll_id, :body, :ord)
    end
  end
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
    before_action :require_signed_in!
  end
end

app/controllers/api/polls_controller.rb
module Api
  class PollsController < ApiController
    # inherits current_user < ApiController < ApplicationController
    # authored_polls is an association on the User model
    wrap_parameters(:poll, :include => [:body, :answer_choices_attributes])

    def create
      @poll = current_user.authored_polls.new(poll_params)
      
      if @poll.save
        render json: @poll
      else
        flash.now[:errors] = @poll.errors.full_messages
        render json: @poll.errors.full_messages, status: :unprocessable_entity
      end
    end
    
    def destroy
      @poll = current_user.authored_polls.find(params[:id])
      @poll.try(:destroy)
      render json: {}
    end

    def index
      if params[:answered] == "false"
        @polls = Poll.where.not(id: current_user.answered_polls).order(id: :desc)
      else
        @polls = current_user.answered_polls.order("responses.id DESC")
      end
      @polls = @polls.includes(:responses).page(params[:page])
      @page_number = params[:page]
      @total_pages = @polls.total_pages
      render :index
    end
    
    def show
      @poll = Poll.find(params[:id])
      render :show
    end
    
    private
    
    def poll_params
      params.require(:poll).permit(:body, :answer_choices_attributes => [:body, :ord])
    end    
  end
end

app/controllers/api/responses_controller.rb
module Api
  class ResponsesController < ApiController
    def create
      @response = current_user.responses.new(response_params)
      
      if @response.save
        render json: @response
      else
        render json: @response.errors.full_messages, status: :unprocessable_entity
      end
    end
    
    private
    
    def response_params
      params.require(:response).permit(:answer_choice_id)
    end
  end
end

app/controllers/api/urls_controller.rb
class Api::UrlsController < ApplicationController
  def shorten
    url = Googl.shorten(params[:long_url])
    render json: { short_url: url.short_url }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :signed_in?

  private

  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in!(user)
    @current_user = user
    session[:token] = user.reset_token!
  end

  def sign_out!
    current_user.try(:reset_token!)
    session[:token] = nil
  end

  def require_signed_in!
    unless signed_in?
      redirect_to new_session_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new 
  end

  def create
    @user = User.find_by_credentials(params[:user])

    if @user
      sign_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Invalid email and/or password"]
      render :new
    end
  end

  def destroy
    sign_out!
    redirect_to new_session_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_signed_in!

  def root 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new()
  end
  
  def create
    @user = params[:user] ? User.new(user_params) : User.new_guest
  
    if @user.save
      sign_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/api/urls_helper.rb
module Api::UrlsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PollTheWorld</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script>
    CURRENT_USER_ID = <%= current_user ? current_user.id : "undefined" %>
  </script>
</head>
<body>
    <!-- Top-Level Navbar -->
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button
            type="button"
            class="navbar-toggle collapsed"
            data-toggle="collapse"
            data-target="#nav-bar">
          <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
          </button>
          <a id="nav-brand" class="navbar-brand" href="#">Poll The World</a>
        </div>
        <!-- Navbar items that will collapse into a button w/ narrow widths -->
        <div class="collapse navbar-collapse" id="nav-bar">
          <ul id="top-nav-bar" class="nav navbar-nav">
            <li id="nav-unanswered"><a href="#">Available Polls</a></li>
            <li id="nav-owned"><a href="/#/polls/new">Create A Poll</a></li>
	    <li id="nav-answered"><a href="/#/polls/answered">Answered Polls</a></li>
          </ul>
          <!-- Sign In Dropdown - still part of Navbar -->
            <% if signed_in? %>
              <%= link_to "Sign Out", session_url, method: :delete, class: "btn btn-primary pull-right" %>
            <% else %>
            <div class="pull-right">
              <button 
                class="btn btn-primary"
                type="button"
                data-toggle="dropdown">
                Not Signed In?
                <span class="caret"></span>
              </button>
            <ul class="dropdown-menu">
              <!-- <li><a href="javascript:void(0)" id="contact-link"> -->
              <li><%= link_to "Sign in", new_session_url %></li>
              <li><%= link_to "Sign up", new_user_url %></li>
            </ul>
            </div>
            <% end %>
          
        </div>
      </div>
    </nav>
    
    <!-- Flash Notices -->
    <% if flash[:errors] %>
    <div class="alert alert-danger" role="alert">
      <h3>Please fix the following errors:</h3>
      <ul>
        <% flash[:errors].each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
    <% end %>


    <!-- Need to wrap yielded view in a container div -->
    <div class="container">
      <%= yield %>
    </div>
  </body>

</html>

app/views/static_pages/root.html.erb
<div id="content"></div>

<script>
$(PollApp.initialize);
</script>

app/views/users/_form.html.erb
<form action="<%= action %>" class="auth_form" method="post" role="form">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <div class="form-group">
    <label for="user_username">Username</label>
    <input
      class="form-control"
      id="user_username"
      name="user[username]"
      type="text">
  </div>

  <div class="form-group">
    <label for="user_password">Password</label>
    <input
      class="form-control"
      id="user_password"
      name="user[password]"
      type="password">
  </div>

  <button class="btn btn-primary submit-auth"><%= message %></button>
</form>

app/views/users/_guest_login.html.erb
<div class="col-xs-3 col-xs-offset-1">
  <h1>Potential Employers</h1>
  <%= button_to "Guest Login", users_url, method: :post, class: "btn btn-primary guest-login" %>

</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-4 col-xs-offset-1">
    <h1>Sign Up</h1>

        <%= render partial: "form", locals: { action: users_url, message: "Sign Up" } %>
  </div>
  <%= render partial: "guest_login" %>
</div>